### ISSUE TITLE
create temporary repositories for write operations

### ISSUE THREAD

**Issue by gr2m** [gr2m/octokit-fixtures#23]
I discussed with @kytrinyx that the repositories we create with the fixtures accounts and on the fixtures organization are all to be used read-only. For scenarios that need write operations, temporary repositories should be created. 

I’ll make a follow up PR for https://github.com/gr2m/octokit-fixtures/pull/16 to create a temporary repository the "add and remove repository collaborators" test

**Comment by kytrinyx** [comment]
> all to be used read-only

I don't necessarily think all of them should be, but it would be nice to have at least one that is so that we can have clear expectations.
